spring:
  profiles:
    active: local
  application:
    name: P-Prism
  ai:
#    mcp:
#      client:
#        stdio:
#          servers-configuration: classpath:mcp-server.json
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen3.7-flash-2026-07-15
          multi-model: true
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1024
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
  datasource:
    url: jdbc:postgresql://localhost:5433/p-prism
    username: postgres
    password: root
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.pp.pprism.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
